# Determin Porygon DT of Sampled Users to Each Restaurant

We get the data from big query.

User Location: sampled (around 700) taking the time period of one week 2020/03/17 - 2020/03/23
Restaurant: active restaurant in 2020 (2046)

In [1]:
# load packages
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pandas.io import gbq
from google.cloud import bigquery
cwd=os.getcwd()
cwd

'C:\\Users\\y.zhang\\Documents\\Projects\\bigquery'

In [2]:
query="""
select * from `fulfillment-dwh-production.temp.results_tw_7`
"""

In [3]:
# run the query and save the results as data frame named df
df=gbq.read_gbq(query,project_id="fulfillment-dwh-production")
# get first 10 rows of datasets
df.head()

Downloading: 100%|████████████████████████████████████████████████████| 11256429/11256429 [13:15<00:00, 14153.88rows/s]

,user_zone_id,geohash,geohash_center,restaurant_id,weight,porygon_dt
0,6,wsqqqn6,POINT(121.556167602539 25.0399017333984),b0ew,88.0,20
1,7,wsqqtnq,POINT(121.517715454102 25.0838470458984),d1dx,81.0,3
2,10,wsqqkbw,POINT(121.506729125977 25.0083160400391),d7us,81.0,12
3,10,wsqqhyj,POINT(121.505355834961 24.9945831298828),y0nu,81.0,6
4,3,wsqq7g9,POINT(121.455917358398 25.0247955322266),e2zv,82.0,18

In [5]:
pivot=df.pivot_table("restaurant_id", index=['geohash_center',"geohash","weight"], columns='porygon_dt', aggfunc='count')
pivot.head()

,,porygon_dt,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
geohash_center,geohash,weight,,,,,,,,,,,,,,,,,,,
POINT(121.343307495117 25.0440216064453),wsqq3pp,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,4.0,4.0,10.0,16.0,31.0,34.0,40.0,25.0,24.0,14.0
POINT(121.343307495117 25.0838470458984),wsqq9nr,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,3.0,2.0,4.0,11.0,23.0,39.0,25.0,8.0,11.0,26.0,43.0
POINT(121.343307495117 25.0865936279297),wsqq9nz,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,3.0,NaN,5.0,15.0,25.0,35.0,23.0,7.0,12.0,26.0
POINT(121.344680786133 25.0399017333984),wsqq3q2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,7.0,14.0,6.0,31.0,42.0,39.0,43.0,5.0,7.0
POINT(121.344680786133 25.0412750244141),wsqq3q8,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,2.0,7.0,14.0,7.0,35.0,41.0,42.0,30.0,9.0,15.0

In [104]:
pivot_cumsum = pivot.cumsum(axis=1)
pivot_cumsum = pivot_cumsum.fillna(0) # replace NA with 0
pivot_cumsum.head()

,,porygon_dt,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
geohash_center,geohash,weight,,,,,,,,,,,,,,,,,,,
POINT(121.343307495117 25.0440216064453),wsqq3pp,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,6.0,10.0,20.0,36.0,67.0,101.0,141.0,166.0,190.0,204.0
POINT(121.343307495117 25.0838470458984),wsqq9nr,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,5.0,7.0,11.0,22.0,45.0,84.0,109.0,117.0,128.0,154.0,197.0
POINT(121.343307495117 25.0865936279297),wsqq9nz,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,6.0,0.0,11.0,26.0,51.0,86.0,109.0,116.0,128.0,154.0
POINT(121.344680786133 25.0399017333984),wsqq3q2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,9.0,23.0,29.0,60.0,102.0,141.0,184.0,189.0,196.0
POINT(121.344680786133 25.0412750244141),wsqq3q8,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,4.0,11.0,25.0,32.0,67.0,108.0,150.0,180.0,189.0,204.0

# Weighted version

In [121]:
weight = pivot_cumsum
weight = weight.reset_index()
weight

porygon_dt,geohash_center,geohash,weight,2,3,4,5,6,7,8,...,11,12,13,14,15,16,17,18,19,20
0,POINT(121.343307495117 25.0440216064453),wsqq3pp,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,6.0,10.0,20.0,36.0,67.0,101.0,141.0,166.0,190.0,204.0
1,POINT(121.343307495117 25.0838470458984),wsqq9nr,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,7.0,11.0,22.0,45.0,84.0,109.0,117.0,128.0,154.0,197.0
2,POINT(121.343307495117 25.0865936279297),wsqq9nz,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.0,0.0,11.0,26.0,51.0,86.0,109.0,116.0,128.0,154.0
3,POINT(121.344680786133 25.0399017333984),wsqq3q2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,9.0,23.0,29.0,60.0,102.0,141.0,184.0,189.0,196.0
4,POINT(121.344680786133 25.0412750244141),wsqq3q8,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,4.0,11.0,25.0,32.0,67.0,108.0,150.0,180.0,189.0,204.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14118,POINT(121.674270629883 25.0824737548828),wsqw8y0,6.0,0.0,0.0,2.0,0.0,4.0,0.0,10.0,...,48.0,66.0,82.0,107.0,115.0,127.0,131.0,138.0,141.0,148.0
14119,POINT(121.675643920898 25.0797271728516),wsqw8v9,10.0,0.0,0.0,1.0,0.0,2.0,4.0,0.0,...,33.0,51.0,68.0,84.0,108.0,119.0,126.0,132.0,139.0,141.0
14120,POINT(121.675643920898 25.0811004638672),wsqw8vc,16.0,0.0,0.0,1.0,0.0,3.0,4.0,0.0,...,36.0,56.0,71.0,86.0,110.0,121.0,129.0,132.0,140.0,143.0
14121,POINT(121.675643920898 25.0838470458984),wsqw8y3,2.0,0.0,0.0,1.0,2.0,3.0,0.0,4.0,...,37.0,56.0,68.0,91.0,110.0,119.0,129.0,134.0,139.0,142.0
14122,POINT(121.677017211914 25.0852203369141),wsqw8yd,1.0,0.0,0.0,0.0,0.0,2.0,3.0,4.0,...,26.0,40.0,59.0,74.0,95.0,111.0,122.0,129.0,134.0,139.0

In [142]:
weight["new"] = weight[20]
weight

porygon_dt,geohash_center,geohash,weight,2,3,4,5,6,7,8,...,12,13,14,15,16,17,18,19,20,new
0,POINT(121.343307495117 25.0440216064453),wsqq3pp,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,10.0,20.0,36.0,67.0,101.0,141.0,166.0,190.0,204.0,204.0
1,POINT(121.343307495117 25.0838470458984),wsqq9nr,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,11.0,22.0,45.0,84.0,109.0,117.0,128.0,154.0,197.0,197.0
2,POINT(121.343307495117 25.0865936279297),wsqq9nz,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,11.0,26.0,51.0,86.0,109.0,116.0,128.0,154.0,154.0
3,POINT(121.344680786133 25.0399017333984),wsqq3q2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,9.0,23.0,29.0,60.0,102.0,141.0,184.0,189.0,196.0,196.0
4,POINT(121.344680786133 25.0412750244141),wsqq3q8,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,11.0,25.0,32.0,67.0,108.0,150.0,180.0,189.0,204.0,204.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14118,POINT(121.674270629883 25.0824737548828),wsqw8y0,6.0,0.0,0.0,2.0,0.0,4.0,0.0,10.0,...,66.0,82.0,107.0,115.0,127.0,131.0,138.0,141.0,148.0,148.0
14119,POINT(121.675643920898 25.0797271728516),wsqw8v9,10.0,0.0,0.0,1.0,0.0,2.0,4.0,0.0,...,51.0,68.0,84.0,108.0,119.0,126.0,132.0,139.0,141.0,141.0
14120,POINT(121.675643920898 25.0811004638672),wsqw8vc,16.0,0.0,0.0,1.0,0.0,3.0,4.0,0.0,...,56.0,71.0,86.0,110.0,121.0,129.0,132.0,140.0,143.0,143.0
14121,POINT(121.675643920898 25.0838470458984),wsqw8y3,2.0,0.0,0.0,1.0,2.0,3.0,0.0,4.0,...,56.0,68.0,91.0,110.0,119.0,129.0,134.0,139.0,142.0,142.0
14122,POINT(121.677017211914 25.0852203369141),wsqw8yd,1.0,0.0,0.0,0.0,0.0,2.0,3.0,4.0,...,40.0,59.0,74.0,95.0,111.0,122.0,129.0,134.0,139.0,139.0

In [141]:
weight.loc[weight[2] >= 1, "weight"].sum()

283795.0

In [157]:
numOfRestaurants = [1, 5, 10, 15, 20, 25, 30]
drivingTimesinMin = range(2,21)
resArray = []
for indexNumOfRestaurants in numOfRestaurants:
    sumByDrivingTimes = []
    for indexDrivingTimesInMin in drivingTimesinMin:
        sumByDrivingTimes.append(weight.loc[weight[indexDrivingTimesInMin] >= indexNumOfRestaurants, "weight"].sum())
        
    sumByDrivingTimes.insert(0,indexNumOfRestaurants)
    resArray.append(sumByDrivingTimes)

resArray

[[1,
  283795.0,
  323575.0,
  335912.0,
  341094.0,
  343542.0,
  345161.0,
  345893.0,
  346892.0,
  347362.0,
  347901.0,
  347548.0,
  347012.0,
  346640.0,
  346695.0,
  345051.0,
  342467.0,
  334634.0,
  326331.0,
  317919.0],
 [5,
  172925.0,
  287148.0,
  320256.0,
  333205.0,
  339458.0,
  342705.0,
  344336.0,
  345837.0,
  346856.0,
  347632.0,
  347414.0,
  346960.0,
  346612.0,
  346675.0,
  345048.0,
  342460.0,
  334630.0,
  326330.0,
  317917.0],
 [10,
  98614.0,
  250095.0,
  304002.0,
  324244.0,
  334188.0,
  339909.0,
  342517.0,
  344311.0,
  345940.0,
  346974.0,
  347129.0,
  346797.0,
  346517.0,
  346628.0,
  345015.0,
  342442.0,
  334625.0,
  326325.0,
  317910.0],
 [15,
  54576.0,
  212324.0,
  287144.0,
  315765.0,
  329563.0,
  336791.0,
  340832.0,
  343053.0,
  344751.0,
  346198.0,
  346556.0,
  346429.0,
  346299.0,
  346523.0,
  344944.0,
  342407.0,
  334607.0,
  326320.0,
  317909.0],
 [20,
  31444.0,
  177331.0,
  269351.0,
  307130.0,
  324495.0,
  334273.0,
  338993.0,
  342041.0,
  343791.0,
  345368.0,
  346003.0,
  345775.0,
  345942.0,
  346231.0,
  344823.0,
  342368.0,
  334549.0,
  326283.0,
  317899.0],
 [25,
  17716.0,
  148490.0,
  250762.0,
  296481.0,
  317431.0,
  329679.0,
  336870.0,
  340823.0,
  343043.0,
  344718.0,
  345579.0,
  345319.0,
  345581.0,
  345949.0,
  344723.0,
  342235.0,
  334511.0,
  326253.0,
  317887.0],
 [30,
  9783.0,
  122788.0,
  234438.0,
  286240.0,
  311534.0,
  324393.0,
  332741.0,
  338380.0,
  341895.0,
  344027.0,
  344863.0,
  345109.0,
  345256.0,
  345623.0,
  344385.0,
  342049.0,
  334383.0,
  326218.0,
  317856.0]]

In [160]:
colNames = np.append("Number of Restaurants", drivingTimesinMin)

df2 = pd.DataFrame(resArray,
                   columns = colNames)

In [161]:
df2

,Number of Restaurants,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
0,1,283795.0,323575.0,335912.0,341094.0,343542.0,345161.0,345893.0,346892.0,347362.0,347901.0,347548.0,347012.0,346640.0,346695.0,345051.0,342467.0,334634.0,326331.0,317919.0
1,5,172925.0,287148.0,320256.0,333205.0,339458.0,342705.0,344336.0,345837.0,346856.0,347632.0,347414.0,346960.0,346612.0,346675.0,345048.0,342460.0,334630.0,326330.0,317917.0
2,10,98614.0,250095.0,304002.0,324244.0,334188.0,339909.0,342517.0,344311.0,345940.0,346974.0,347129.0,346797.0,346517.0,346628.0,345015.0,342442.0,334625.0,326325.0,317910.0
3,15,54576.0,212324.0,287144.0,315765.0,329563.0,336791.0,340832.0,343053.0,344751.0,346198.0,346556.0,346429.0,346299.0,346523.0,344944.0,342407.0,334607.0,326320.0,317909.0
4,20,31444.0,177331.0,269351.0,307130.0,324495.0,334273.0,338993.0,342041.0,343791.0,345368.0,346003.0,345775.0,345942.0,346231.0,344823.0,342368.0,334549.0,326283.0,317899.0
5,25,17716.0,148490.0,250762.0,296481.0,317431.0,329679.0,336870.0,340823.0,343043.0,344718.0,345579.0,345319.0,345581.0,345949.0,344723.0,342235.0,334511.0,326253.0,317887.0
6,30,9783.0,122788.0,234438.0,286240.0,311534.0,324393.0,332741.0,338380.0,341895.0,344027.0,344863.0,345109.0,345256.0,345623.0,344385.0,342049.0,334383.0,326218.0,317856.0

In [164]:
totalnum = weight["weight"].sum()
totalnum

In [173]:
df2[["2","3","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20"]].div(totalnum)

,2,3,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
0,0.812068,0.925897,0.925897,0.961199,0.976027,0.983032,0.987664,0.989759,0.992617,0.993962,0.995505,0.994495,0.992961,0.991896,0.992054,0.987349,0.979955,0.957542,0.933783,0.909712
1,0.494818,0.821662,0.821662,0.916400,0.953453,0.971345,0.980637,0.985304,0.989599,0.992514,0.994735,0.994111,0.992812,0.991816,0.991996,0.987341,0.979935,0.957530,0.933780,0.909707
2,0.282180,0.715637,0.715637,0.869889,0.927811,0.956265,0.972636,0.980099,0.985232,0.989893,0.992852,0.993296,0.992346,0.991544,0.991862,0.987246,0.979884,0.957516,0.933766,0.909687
3,0.156167,0.607557,0.607557,0.821651,0.903549,0.943031,0.963714,0.975277,0.981632,0.986491,0.990632,0.991656,0.991293,0.990921,0.991562,0.987043,0.979784,0.957464,0.933751,0.909684
4,0.089976,0.507425,0.507425,0.770737,0.878840,0.928529,0.956509,0.970015,0.978736,0.983744,0.988257,0.990074,0.989421,0.989899,0.990726,0.986697,0.979672,0.957298,0.933646,0.909655
5,0.050694,0.424898,0.424898,0.717545,0.848368,0.908316,0.943363,0.963940,0.975251,0.981604,0.986397,0.988860,0.988116,0.988866,0.989919,0.986411,0.979292,0.957190,0.933560,0.909621
6,0.027994,0.351353,0.351353,0.670835,0.819064,0.891442,0.928237,0.952125,0.968261,0.978319,0.984419,0.986812,0.987515,0.987936,0.988986,0.985444,0.978759,0.956823,0.933460,0.909532

## Non-weighted version

In [29]:
result = pivot_cumsum.apply(pd.value_counts).fillna(0)
result["index"]=result.index
result

porygon_dt,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,index
0.0,6279.0,3467.0,2184.0,1485.0,1052.0,805.0,587.0,404.0,334.0,254.0,220.0,197.0,230.0,182.0,232.0,303.0,528.0,756.0,1084.0,0.0
1.0,1623.0,926.0,464.0,299.0,171.0,78.0,59.0,34.0,25.0,6.0,10.0,5.0,5.0,1.0,1.0,2.0,0.0,0.0,2.0,1.0
2.0,994.0,731.0,465.0,261.0,188.0,131.0,80.0,58.0,28.0,21.0,5.0,5.0,2.0,3.0,0.0,2.0,1.0,0.0,0.0,2.0
3.0,782.0,551.0,417.0,288.0,176.0,129.0,96.0,74.0,41.0,21.0,16.0,2.0,3.0,0.0,1.0,1.0,2.0,1.0,0.0,3.0
4.0,607.0,437.0,319.0,203.0,164.0,112.0,88.0,63.0,33.0,32.0,34.0,15.0,5.0,5.0,1.0,1.0,0.0,0.0,0.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3529.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3529.0
3534.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3534.0
3542.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3542.0
3544.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3544.0
3545.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3545.0

In [84]:
pivot_cumsum

,,porygon_dt,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,index
geohash_center,geohash,weight,,,,,,,,,,,,,,,,,,,,
POINT(121.343307495117 25.0440216064453),wsqq3pp,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,6.0,10.0,20.0,36.0,67.0,101.0,141.0,166.0,190.0,204.0,"(POINT(121.343307495117 25.0440216064453), wsq..."
POINT(121.343307495117 25.0838470458984),wsqq9nr,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,5.0,7.0,11.0,22.0,45.0,84.0,109.0,117.0,128.0,154.0,197.0,"(POINT(121.343307495117 25.0838470458984), wsq..."
POINT(121.343307495117 25.0865936279297),wsqq9nz,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,6.0,0.0,11.0,26.0,51.0,86.0,109.0,116.0,128.0,154.0,"(POINT(121.343307495117 25.0865936279297), wsq..."
POINT(121.344680786133 25.0399017333984),wsqq3q2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,9.0,23.0,29.0,60.0,102.0,141.0,184.0,189.0,196.0,"(POINT(121.344680786133 25.0399017333984), wsq..."
POINT(121.344680786133 25.0412750244141),wsqq3q8,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,4.0,11.0,25.0,32.0,67.0,108.0,150.0,180.0,189.0,204.0,"(POINT(121.344680786133 25.0412750244141), wsq..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
POINT(121.674270629883 25.0824737548828),wsqw8y0,6.0,0.0,0.0,2.0,0.0,4.0,0.0,10.0,27.0,30.0,48.0,66.0,82.0,107.0,115.0,127.0,131.0,138.0,141.0,148.0,"(POINT(121.674270629883 25.0824737548828), wsq..."
POINT(121.675643920898 25.0797271728516),wsqw8v9,10.0,0.0,0.0,1.0,0.0,2.0,4.0,0.0,10.0,24.0,33.0,51.0,68.0,84.0,108.0,119.0,126.0,132.0,139.0,141.0,"(POINT(121.675643920898 25.0797271728516), wsq..."
POINT(121.675643920898 25.0811004638672),wsqw8vc,16.0,0.0,0.0,1.0,0.0,3.0,4.0,0.0,13.0,28.0,36.0,56.0,71.0,86.0,110.0,121.0,129.0,132.0,140.0,143.0,"(POINT(121.675643920898 25.0811004638672), wsq..."
POINT(121.675643920898 25.0838470458984),wsqw8y3,2.0,0.0,0.0,1.0,2.0,3.0,0.0,4.0,15.0,24.0,37.0,56.0,68.0,91.0,110.0,119.0,129.0,134.0,139.0,142.0,"(POINT(121.675643920898 25.0838470458984), wsq..."
POINT(121.677017211914 25.0852203369141),wsqw8yd,1.0,0.0,0.0,0.0,0.0,2.0,3.0,4.0,6.0,19.0,26.0,40.0,59.0,74.0,95.0,111.0,122.0,129.0,134.0,139.0,"(POINT(121.677017211914 25.0852203369141), wsq..."

In [38]:
column1=result[result["index"]>=1].sum()
column5=result[result["index"]>=5].sum()
column10=result[result["index"]>=10].sum()
column15=result[result["index"]>=15].sum()
column20=result[result["index"]>=20].sum()
column25=result[result["index"]>=25].sum()
column30=result[result["index"]>=30].sum()

In [45]:
aggregate=pd.concat([column1, column5, column10, column15, column20, column25, column30], axis=1)
aggregate.columns = [1,5,10,15,20,25,30]
aggregate=aggregate.T
aggregate

porygon_dt,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,index
1,7844.0,10656.0,11939.0,12638.0,13071.0,13318.0,13536.0,13719.0,13789.0,13869.0,13903.0,13926.0,13893.0,13941.0,13891.0,13820.0,13595.0,13367.0,13039.0,5472393.0
5,3838.0,8011.0,10274.0,11587.0,12372.0,12868.0,13213.0,13490.0,13662.0,13789.0,13838.0,13899.0,13878.0,13932.0,13888.0,13814.0,13592.0,13366.0,13037.0,5472383.0
10,1999.0,6358.0,9088.0,10715.0,11762.0,12476.0,12907.0,13213.0,13467.0,13670.0,13759.0,13849.0,13842.0,13913.0,13877.0,13805.0,13587.0,13362.0,13031.0,5472348.0
15,1052.0,5052.0,8122.0,10056.0,11266.0,12082.0,12659.0,13002.0,13274.0,13534.0,13661.0,13772.0,13786.0,13877.0,13857.0,13795.0,13577.0,13358.0,13030.0,5472288.0
20,582.0,4012.0,7245.0,9411.0,10836.0,11763.0,12440.0,12851.0,13117.0,13404.0,13555.0,13675.0,13724.0,13825.0,13827.0,13781.0,13560.0,13343.0,13024.0,5472203.0
25,320.0,3248.0,6485.0,8799.0,10266.0,11374.0,12171.0,12670.0,12994.0,13292.0,13467.0,13601.0,13672.0,13787.0,13803.0,13751.0,13546.0,13336.0,13018.0,5472093.0
30,171.0,2594.0,5840.0,8233.0,9855.0,10970.0,11805.0,12424.0,12842.0,13179.0,13375.0,13535.0,13604.0,13731.0,13761.0,13723.0,13522.0,13321.0,13011.0,5471958.0

In [163]:
aggregate[[2,3,4,5,6,7,8,9,10,11,12,12,14,15,16,17,18,19,20]].div(13950)

porygon_dt,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
1,0.562294,0.763871,0.855842,0.905950,0.936989,0.954695,0.970323,0.983441,0.988459,0.994194,0.996631,0.998280,0.995914,0.999355,0.995771,0.990681,0.974552,0.958208,0.934695
5,0.275125,0.574265,0.736487,0.830609,0.886882,0.922437,0.947168,0.967025,0.979355,0.988459,0.991971,0.996344,0.994839,0.998710,0.995556,0.990251,0.974337,0.958136,0.934552
10,0.143297,0.455771,0.651470,0.768100,0.843154,0.894337,0.925233,0.947168,0.965376,0.979928,0.986308,0.992760,0.992258,0.997348,0.994767,0.989606,0.973978,0.957849,0.934122
15,0.075412,0.362151,0.582222,0.720860,0.807599,0.866093,0.907455,0.932043,0.951541,0.970179,0.979283,0.987240,0.988244,0.994767,0.993333,0.988889,0.973262,0.957563,0.934050
20,0.041720,0.287599,0.519355,0.674624,0.776774,0.843226,0.891756,0.921219,0.940287,0.960860,0.971685,0.980287,0.983799,0.991039,0.991183,0.987885,0.972043,0.956487,0.933620
25,0.022939,0.232832,0.464875,0.630753,0.735914,0.815341,0.872473,0.908244,0.931470,0.952832,0.965376,0.974982,0.980072,0.988315,0.989462,0.985735,0.971039,0.955986,0.933190
30,0.012258,0.185950,0.418638,0.590179,0.706452,0.786380,0.846237,0.890609,0.920573,0.944731,0.958781,0.970251,0.975197,0.984301,0.986452,0.983728,0.969319,0.954910,0.932688